// City coordinates for Texas
// Auto-generated by Tour Stop Importer

export const cityCoordinates: Record<string, { lat: number, lon: number }> = {
    'Liberty Hill': { lat: 30.6660, lon: -97.9225 },
    'Austin': { lat: 30.2672, lon: -97.7431 },
    'Georgetown': { lat: 30.6327, lon: -97.6769 },
    'San Antonio': { lat: 29.4241, lon: -98.4936 },
    'Houston': { lat: 29.7604, lon: -95.3698 },
    'Dallas': { lat: 32.7767, lon: -96.7970 },
    'Fort Worth': { lat: 32.7555, lon: -97.3308 },
    'El Paso': { lat: 31.7619, lon: -106.4850 },
    'Amarillo': { lat: 35.2220, lon: -101.8313 },
    'Lubbock': { lat: 33.5779, lon: -101.8552 },
    'Corpus Christi': { lat: 27.8006, lon: -97.3964 },
    'Abilene': { lat: 32.4487, lon: -99.7331 },
    'Waco': { lat: 31.5493, lon: -97.1467 },
    'Midland': { lat: 31.9973, lon: -102.0779 },
    'Tyler': { lat: 32.3513, lon: -95.3011 }
  };